platform :ios,'8.0'
target 'yf-jd-phone' do
pod 'MJExtension', '~> 3.0.10'
pod 'AFNetworking','~> 3.0.4'
pod 'SDWebImage', '~> 3.7.5'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDCycleScrollView', '~> 1.61'
end
